# Dockerfile.nodejs
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Expose the port and set the default command
EXPOSE 3000
CMD ["npm", "start"]